"""add execution observability

Revision ID: 9f4c2d7e8a11
Revises: 76537556b265
Create Date: 2026-08-13 15:40:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "9f4c2d7e8a11"
down_revision: Union[str, Sequence[str], None] = "76537556b265"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "execution_traces",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "execution_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "task_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "trace_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "wall_clock_ms",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "total_input_tokens",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_output_tokens",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_tokens",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_tool_calls",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_cost",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "attributes",
            sa.JSON(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id"),
        sa.UniqueConstraint("trace_id"),
    )
    op.create_index(
        "ix_execution_traces_execution_id",
        "execution_traces",
        ["execution_id"],
    )
    op.create_index(
        "ix_execution_traces_task_id",
        "execution_traces",
        ["task_id"],
    )
    op.create_index(
        "ix_execution_traces_trace_id",
        "execution_traces",
        ["trace_id"],
    )

    op.create_table(
        "execution_trace_spans",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "trace_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "span_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "parent_span_id",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "execution_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "agent",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "specialist",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "subtask_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "tool_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "provider",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "model",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "duration_ms",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "input",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "output",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "prompt",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "raw_response",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "error",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "total_tokens",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "cost",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "attributes",
            sa.JSON(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("span_id"),
    )
    op.create_index(
        "ix_execution_trace_spans_trace_id",
        "execution_trace_spans",
        ["trace_id"],
    )
    op.create_index(
        "ix_execution_trace_spans_span_id",
        "execution_trace_spans",
        ["span_id"],
    )
    op.create_index(
        "ix_execution_trace_spans_parent_span_id",
        "execution_trace_spans",
        ["parent_span_id"],
    )
    op.create_index(
        "ix_execution_trace_spans_execution_id",
        "execution_trace_spans",
        ["execution_id"],
    )
    op.create_index(
        "ix_execution_trace_spans_subtask_id",
        "execution_trace_spans",
        ["subtask_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_execution_trace_spans_subtask_id",
        table_name="execution_trace_spans",
    )
    op.drop_index(
        "ix_execution_trace_spans_execution_id",
        table_name="execution_trace_spans",
    )
    op.drop_index(
        "ix_execution_trace_spans_parent_span_id",
        table_name="execution_trace_spans",
    )
    op.drop_index(
        "ix_execution_trace_spans_span_id",
        table_name="execution_trace_spans",
    )
    op.drop_index(
        "ix_execution_trace_spans_trace_id",
        table_name="execution_trace_spans",
    )
    op.drop_table("execution_trace_spans")

    op.drop_index(
        "ix_execution_traces_trace_id",
        table_name="execution_traces",
    )
    op.drop_index(
        "ix_execution_traces_task_id",
        table_name="execution_traces",
    )
    op.drop_index(
        "ix_execution_traces_execution_id",
        table_name="execution_traces",
    )
    op.drop_table("execution_traces")
