"""create initial persistence schema

Revision ID: a1dac09fca43
Revises: 
Create Date: 2026-08-10 17:04:45.767980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dac09fca43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_task_id'), 'executions', ['task_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_execution_id'), 'reviews', ['execution_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('assigned_specialist', sa.String(length=50), nullable=False),
    sa.Column('expected_output', sa.String(length=2000), nullable=False),
    sa.Column('estimated_complexity', sa.String(length=20), nullable=False),
    sa.Column('required_inputs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_execution_id'), 'subtasks', ['execution_id'], unique=False)
    op.create_table('subtask_dependencies',
    sa.Column('subtask_id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['subtasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtask_id', 'dependency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtask_dependencies')
    op.drop_index(op.f('ix_subtasks_execution_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_reviews_execution_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_executions_task_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
