from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field, model_validator


class Specialist(StrEnum):
    """
    Specialist agent domains defined by Project 15.
    """

    RESEARCH = "research"
    DATA_ANALYSIS = "data_analysis"
    WRITING = "writing"
    CODE_EXECUTION = "code_execution"


class Complexity(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class SubTask(BaseModel):
    """
    A single unit of work generated by the Supervisor.
    """

    id: UUID

    description: str = Field(
        min_length=1,
        description="Specific work the specialist must perform.",
    )

    assigned_specialist: Specialist = Field(
        description="Specialist responsible for this subtask.",
    )

    required_inputs: list[str] = Field(
        default_factory=list,
        description="Inputs required before this subtask can execute.",
    )

    expected_output: str = Field(
        min_length=1,
        description="Expected structure or content of the result.",
    )

    estimated_complexity: Complexity

    dependencies: list[UUID] = Field(
        default_factory=list,
        description="IDs of subtasks that must complete first.",
    )

    @model_validator(mode="after")
    def validate_dependencies(self) -> "SubTask":
        if self.id in self.dependencies:
            raise ValueError("A subtask cannot depend on itself.")

        return self


class ExecutionPlan(BaseModel):
    """
    Structured plan produced by the Supervisor.
    """

    task_id: UUID

    subtasks: list[SubTask] = Field(
        min_length=1,
        description="Ordered set of subtasks required to complete the task.",
    )

    @model_validator(mode="after")
    def validate_plan_dependencies(self) -> "ExecutionPlan":
        subtask_ids = {subtask.id for subtask in self.subtasks}

        for subtask in self.subtasks:
            missing = set(subtask.dependencies) - subtask_ids

            if missing:
                raise ValueError(
                    f"Subtask {subtask.id} references unknown dependencies: "
                    f"{sorted(str(item) for item in missing)}"
                )

        return self